[package]
name = "irc_proto"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true
nom.workspace = true
thiserror.workspace = true
